[0;1;32m‚óè[0m gunicorn.service - gunicorn daemon
     Loaded: loaded (/etc/systemd/system/gunicorn.service; enabled; vendor preset: enabled)
     Active: [0;1;32mactive (running)[0m since Sat 2023-10-28 13:47:33 MSK; 4min 42s ago
   Main PID: 39067 (gunicorn)
      Tasks: 2 (limit: 4559)
     Memory: 46.5M
        CPU: 877ms
     CGroup: /system.slice/gunicorn.service
             ‚îú‚îÄ39067 /home/rustam/projects/hw05_final/venv/bin/python3 /home/rustam/projects/hw05_final/venv/bin/gunicorn --bind 127.0.0.1:8000 yatube.wsgi:application
             ‚îî‚îÄ39070 /home/rustam/projects/hw05_final/venv/bin/python3 /home/rustam/projects/hw05_final/venv/bin/gunicorn --bind 127.0.0.1:8000 yatube.wsgi:application

–æ–∫—Ç 28 13:48:45 rustam-QEMU-Virtual-Machine gunicorn[39070]:     raise dj_exc_value.with_traceback(traceback) from exc_value
–æ–∫—Ç 28 13:48:45 rustam-QEMU-Virtual-Machine gunicorn[39070]:   File "/home/rustam/projects/hw05_final/venv/lib/python3.10/site-packages/django/db/backends/base/base.py", line 217, in ensure_connection
–æ–∫—Ç 28 13:48:45 rustam-QEMU-Virtual-Machine gunicorn[39070]:     self.connect()
–æ–∫—Ç 28 13:48:45 rustam-QEMU-Virtual-Machine gunicorn[39070]:   File "/home/rustam/projects/hw05_final/venv/lib/python3.10/site-packages/django/db/backends/base/base.py", line 195, in connect
–æ–∫—Ç 28 13:48:45 rustam-QEMU-Virtual-Machine gunicorn[39070]:     self.connection = self.get_new_connection(conn_params)
–æ–∫—Ç 28 13:48:45 rustam-QEMU-Virtual-Machine gunicorn[39070]:   File "/home/rustam/projects/hw05_final/venv/lib/python3.10/site-packages/django/db/backends/postgresql/base.py", line 178, in get_new_connection
–æ–∫—Ç 28 13:48:45 rustam-QEMU-Virtual-Machine gunicorn[39070]:     connection = Database.connect(**conn_params)
–æ–∫—Ç 28 13:48:45 rustam-QEMU-Virtual-Machine gunicorn[39070]:   File "/home/rustam/projects/hw05_final/venv/lib/python3.10/site-packages/psycopg2/__init__.py", line 122, in connect
–æ–∫—Ç 28 13:48:45 rustam-QEMU-Virtual-Machine gunicorn[39070]:     conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
–æ–∫—Ç 28 13:48:45 rustam-QEMU-Virtual-Machine gunicorn[39070]: django.db.utils.OperationalError: could not translate host name "db" to address: Temporary failure in name resolution
